---
driver:
  name: vagrant
provisioner:
  name: chef_solo
platforms:
  - name: ubuntu-14.04
suites:
  - name: default
    run_list:
      - recipe[gem_server::default]
      - recipe[gem_server::proxy]
    attributes:
