name             'geminabox_chef'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures geminabox_chef'
long_description 'Installs/Configures geminabox_chef'
version          '0.1.0'
